### ISSUE TITLE
Can u control please, if i have some mod conflict?

### ISSUE THREAD

**Issue by roccotommy** [CitiesSkylinesMods/AutoRepair#17]
[TMPE.log](https://github.com/CitiesSkylinesMods/AutoRepair/files/4410225/TMPE.log)
[AutoRepair.log](https://github.com/CitiesSkylinesMods/AutoRepair/files/4410229/AutoRepair.log)
[output_log.txt](https://github.com/CitiesSkylinesMods/AutoRepair/files/4410232/output_log.txt)

**Comment by aubergine10** [comment]
You have very low RAM for this game - 8GB isn't really enough to run the game, ideally you'd need 16GB or more.

See this guide for some additional deatils: https://steamcommunity.com/sharedfiles/filedetails/?id=465790009
